name: Build linux-aarch64-musl

on:
  push:
    branches: ["b*.*.*"]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    container: alpine:3.21
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-target
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
