on:
  push:
    branches: ["b*.*.*"]

jobs:
  build:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-target
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
