on:
  push:
    branches: ["b*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-target
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
